### ISSUE TITLE
Incompatibility with Konkrete 1.9.2

### ISSUE THREAD

**Issue by MightyKnight** [Keksuccino/Panoramica#12]
When updating the required Konkrete library to version 1.9.2 (from 1.8.0), the game crashes because of Panoramica.
Konkrete runs fine without Panoramica.
`Attach error for panoramica.mixin.json:MixinMinecraft from mod panoramica`

There may have been internal library changes between Konkrete 1.8.0 (works) and 1.9.2 (doesn't work) that require changes on your side. Hope that helps.

I copied the launcher output because for some reason my instance didn't generate a crash report.
```
23:41:57.181 FabricLoader/Mixin Render thread
Error loading class: de/keksuccino/konkrete/events/EventBase (java.lang.ClassNotFoundException: de/keksuccino/konkrete/events/EventBase)
23:41:57.181 FabricLoader/Mixin Render thread
Error loading class: de/keksuccino/konkrete/events/EventHandler (java.lang.ClassNotFoundException: de/keksuccino/konkrete/events/EventHandler)
23:41:57.288 FabricLoader/Mixin Render thread
Error loading class: de/keksuccino/konkrete/events/EventBase (java.lang.ClassNotFoundException: de/keksuccino/konkrete/events/EventBase)
23:41:57.289 FabricLoader/Mixin Render thread
Error loading class: de/keksuccino/konkrete/events/EventHandler (java.lang.ClassNotFoundException: de/keksuccino/konkrete/events/EventHandler)
23:41:57.289 FabricLoader Render thread
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.client.main.Main.main(Main.java:233)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for panoramica.mixin.json:MixinMinecraft from mod panoramica during activity: [Transform -> Method onTick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKEVIRTUAL -> de/keksuccino/konkrete/events/EventHandler::callEventsFor:(Lde/keksuccino/konkrete/events/EventBase;)V]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 11 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: de.keksuccino.konkrete.events.EventHandler
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:772)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:738)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 17 more
Caused by: java.lang.ClassNotFoundException: de.keksuccino.konkrete.events.EventHandler
	... 21 more
```

## Other info
Minecraft 1.20.4
Panoramica 1.2.1 for Fabric from Modrinth

**Comment by MightyKnight** [comment]
Thanks, all works.
And I'm actually sorry, I didn't notice you were the author of both. Good work!
